### ISSUE TITLE
can't build wireguard on raspberry pi 1

### ISSUE THREAD

**Issue by owinkelmann** [adrianmihalko/raspberrypiwireguard#14]
pi@raspberrypi ~/WireGuard/src $ make
make[1]: *** /lib/modules/4.14.94+/build: No such file or directory.  Stop. 
Makefile:37: recipe for target 'module' failed
make: *** [module] Error 2

pi@raspberrypi ~/WireGuard/src $ uname -a
Linux raspberrypi 4.14.94+ #1193 Tue Jan 22 15:18:37 GMT 2019 armv6l GNU/Linux

**Comment by adrianmihalko** [comment]
Please try to install kernel sources manually and then reinstall Wireguard.

**0, Install required packages for rpi-source**

    sudo apt-get install bc libncurses5-dev

**1, Install kernel headers via rpi-source**

https://github.com/notro/rpi-source

**Comment by owinkelmann** [comment]
Thank you. Now it works.
