### ISSUE TITLE
Better way to install for Raspberry Pi 2 and above

### ISSUE THREAD

**Issue by ViRb3** [adrianmihalko/raspberrypiwireguard#4]
Following the official WireGuard Debian instructions:

```
# apt install raspberrypi-kernel-headers -y # required to build kernel module
# echo "deb http://deb.debian.org/debian/ unstable main" > /etc/apt/sources.list.d/unstable.list
# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 # add unstable distribution public key
# printf 'Package: *\nPin: release a=unstable\nPin-Priority: 150\n' > /etc/apt/preferences.d/limit-unstable
# apt update
# apt install wireguard
```

**Comment by adrianmihalko** [comment]
I get:

pi@raspberrypi:~ $ sudo wg
Segmentation fault

...using this method.

**Comment by ViRb3** [comment]
Are you sure you are running a Pi 2/3? The older Pi's are missing certain CPU extensions.

**Comment by adrianmihalko** [comment]
I tried on RPi Zero (non Wlan). 

+ one more info I was needed to install 
$ sudo apt-get install dirmngr

to import keys for APT.

**Comment by ViRb3** [comment]
For the Pi Zero follow this:
https://github.com/adrianmihalko/raspberrypiwireguard/issues/3

**Comment by Mehran** [comment]
@ViRb3 I success install WG on RPi3, I also try NAT on wifi for the clients, everything is okay but seems some site like icloud.com ,  fast.com ... site not completely opened and browser status: Established a secure connection.  can you have provided Step by Step for client connect to RPI wifi and `nat `to `wg0`

**Comment by adrianmihalko** [comment]
updated guide
